name: Manager
version: ${project.version}
main: network.warzone.manager.Manager
authors: [MatrixTunnel, JorgeberrexMC]
website: http://warzone.store/
depend: [TGM]

commands:
  issue:
    description: Sends a link to create a GitHub issue
    usage: /issue
  tags:
    description: Select your suffix tag
    aliases: [tag]
    usage: /tags
  manager: {}
  github:
    description: Sends a link to our GitHub
    aliases: [gh]
    usage: /github
  forums:
    description: Sends a link to our forums
    usage: /forums
  store:
    description: Sends a link to our store
    aliases: [shop]
    usage: /store